##
## You provide this
##
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: aisa6148/worker:latest
        #ports:
        #- containerPort:
        # this container needs the environment variables set to specify
        # the hosts of rabbit and redis
        # We are declaring these environment variables of the container before deploying
        env:
          - name: REDIS_HOST
            value: redis
          - name: RABBITMQ_HOST
            value: rabbitmq

---